name: Deploy to heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django tests
      run: |
        python manage.py collectstatic --clear --noinput
        python manage.py makemigrations --check --noinput
        python manage.py check
        python3 manage.py test
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_PRODUCTION}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
    - name: Success
      run: echo Successfully Deployed!!

      